name:                plants-vs-zombies
version:             0.1.0.0
github:              "iu-haskell-fall-2019/plants-vs-zombies"
license:             BSD3
author:              "Alina Chasova, Kamila Borodina"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at 

custom-setup:
  dependencies:
  - base
  - Cabal
  - cabal-doctest >=1.0.2 && <1.1

ghc-options:
- -Wall -fno-warn-type-defaults

dependencies:
- base (>=4.8 && <4.13)
- gloss == 1.13.*
- JuicyPixels == 3.3.3
- bytestring == 0.10.8.2
- JuicyPixels-repa == 0.7.1.0
- repa == 3.4.1.4

library:
  source-dirs: src

executables:
  plants-vs-zombies-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plants-vs-zombies

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plants-vs-zombies
    - hspec
    - HUnit
    - QuickCheck

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
    - base
    - doctest
    - Glob
    - QuickCheck
    - template-haskell
